import '../../../features/debt_ledger/domain/entities/customer_entity.dart';
import '../../../features/debt_ledger/domain/entities/debt_transaction_entity.dart';
import '../../../features/inventory/domain/entities/category_entity.dart';
import '../../../features/pos/domain/entities/product_entity.dart';
import '../../../core/enums/enums.dart';

class BaseetMockData {
  static List<CategoryEntity> initialCategories = [
    const CategoryEntity(id: 'cat_0', name: 'الكل', iconName: 'apps'),
    const CategoryEntity(id: 'cat_1', name: 'المشروبات', iconName: 'local_drink'),
    const CategoryEntity(id: 'cat_2', name: 'البقوليات', iconName: 'grain'),
    const CategoryEntity(id: 'cat_3', name: 'الألبان', iconName: 'egg'),
    const CategoryEntity(id: 'cat_4', name: 'المعلبات', iconName: 'inventory'),
  ];

  static List<ProductEntity> initialProducts = [
    const ProductEntity(
      id: 'prod_1',
      name: 'حليب جهينة 1 لتر',
      barcode: '6221001001',
      categoryId: 'cat_3',
      categoryName: 'الألبان',
      buyPrice: 42.0,
      sellPrice: 50.0,
      stockQuantity: 12,
      minStockLimit: 5,
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=300&q=80',
    ),
    const ProductEntity(
      id: 'prod_2',
      name: 'كوكاكولا كانز 330 مل',
      barcode: '6221001002',
      categoryId: 'cat_1',
      categoryName: 'المشروبات',
      buyPrice: 11.5,
      sellPrice: 15.0,
      stockQuantity: 45,
      minStockLimit: 10,
      imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=300&q=80',
    ),
    const ProductEntity(
      id: 'prod_3',
      name: 'أرز الضحى 1 كجم',
      barcode: '6221001003',
      categoryId: 'cat_2',
      categoryName: 'البقوليات',
      buyPrice: 28.0,
      sellPrice: 35.0,
      stockQuantity: 8,
      minStockLimit: 3,
      imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=300&q=80',
    ),
    const ProductEntity(
      id: 'prod_4',
      name: 'زيت عافية ذرة 800 مل',
      barcode: '6221001004',
      categoryId: 'cat_4',
      categoryName: 'المعلبات',
      buyPrice: 72.0,
      sellPrice: 85.0,
      stockQuantity: 2,
      minStockLimit: 4,
      imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=300&q=80',
    ),
    const ProductEntity(
      id: 'prod_5',
      name: 'شاي العروسة 250 جم',
      barcode: '6221001005',
      categoryId: 'cat_1',
      categoryName: 'المشروبات',
      buyPrice: 40.0,
      sellPrice: 48.0,
      stockQuantity: 20,
      minStockLimit: 5,
      imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=300&q=80',
    ),
    const ProductEntity(
      id: 'prod_6',
      name: 'جبنة دومتي بيضاء 500 جم',
      barcode: '6221001006',
      categoryId: 'cat_3',
      categoryName: 'الألبان',
      buyPrice: 28.0,
      sellPrice: 34.0,
      stockQuantity: 15,
      minStockLimit: 5,
      imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=300&q=80',
    ),
  ];

  static List<CustomerEntity> initialCustomers = [
    CustomerEntity(
      id: 'cust_1',
      name: 'محمد أحمد',
      phone: '01012345678',
      totalDebt: 1200.0,
      creditLimit: 2000.0,
      status: DebtStatus.overdue,
      lastPaymentDate: DateTime.now().subtract(const Duration(days: 14)),
      address: 'شارع التحرير، الدقي',
      notes: 'عميل دائم - يفضل السداد يوم 1 في الشهر',
    ),
    CustomerEntity(
      id: 'cust_2',
      name: 'علي محمود',
      phone: '01198765432',
      totalDebt: 850.0,
      creditLimit: 1500.0,
      status: DebtStatus.regular,
      lastPaymentDate: DateTime.now().subtract(const Duration(days: 2)),
      address: 'شارع فيصل، الجيزة',
      notes: 'منتظم بالسداد أسبوعياً',
    ),
    CustomerEntity(
      id: 'cust_3',
      name: 'سيد إبراهيم',
      phone: '01234567890',
      totalDebt: 3500.0,
      creditLimit: 3000.0,
      status: DebtStatus.limitExceeded,
      lastPaymentDate: DateTime.now().subtract(const Duration(days: 21)),
      address: 'شارع الهرم، الجيزة',
      notes: 'تجاوز الحد الائتماني',
    ),
    CustomerEntity(
      id: 'cust_4',
      name: 'محمود حسن',
      phone: '01555123456',
      totalDebt: 450.0,
      creditLimit: 1000.0,
      status: DebtStatus.regular,
      lastPaymentDate: DateTime.now().subtract(const Duration(days: 1)),
      address: 'المعادي، القاهرة',
    ),
  ];

  static List<DebtTransactionEntity> initialTransactions = [
    DebtTransactionEntity(
      id: 'tx_1',
      customerId: 'cust_1',
      type: TransactionType.saleCredit,
      amount: 450.0,
      date: DateTime.now().subtract(const Duration(days: 14)),
      notes: 'فاتورة مشتريات بقالة #1084',
      remainingBalance: 1200.0,
    ),
    DebtTransactionEntity(
      id: 'tx_2',
      customerId: 'cust_1',
      type: TransactionType.paymentVoucher,
      amount: 500.0,
      date: DateTime.now().subtract(const Duration(days: 20)),
      notes: 'سند قبض نقدي #REC-402',
      remainingBalance: 750.0,
    ),
    DebtTransactionEntity(
      id: 'tx_3',
      customerId: 'cust_2',
      type: TransactionType.paymentVoucher,
      amount: 300.0,
      date: DateTime.now().subtract(const Duration(days: 2)),
      notes: 'سند قبض نقدي #REC-410',
      remainingBalance: 850.0,
    ),
  ];
}
